version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/input.csv
    outputs:
      highly_sensitive:
        dataset: output/input.csv

  data_process:
    run: r:v2 analysis/data_process.R
    needs:
    - generate_dataset
    outputs:
      highly_sensitive:
        rds: output/data_processed.rds
      #moderately_sensitive:
      #  arguments: output/args-data_processed.csv
